/*
* EQUIPO:
* JOSÉ MAURICIO CANUL CHUC
* MARCO ANTONIO TUZ PECH
* RODRIGO ÁNGEL POOT POOT
*/
package metodosnumericos;
/**
 *
 * @author Mauricio
 */
public class MenuMetodos extends javax.swing.JFrame {

    /**
     * Creates new form MenuMetodos
     */
    public MenuMetodos() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        biseccion = new javax.swing.JButton();
        newton = new javax.swing.JButton();
        secante = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        fondo = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Métodos Numéricos");
        setLocation(new java.awt.Point(0, 0));
        setMaximumSize(new java.awt.Dimension(450, 234));
        setResizable(false);
        setSize(new java.awt.Dimension(300, 300));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Métodos de Resolución de Ecuaciones no Lineales");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, 29));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Elija el Método que desee usar");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, -1));

        biseccion.setText("Método de Bisección");
        biseccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biseccionActionPerformed(evt);
            }
        });
        getContentPane().add(biseccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        newton.setText("Método de Newton Rapshon");
        newton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newtonActionPerformed(evt);
            }
        });
        getContentPane().add(newton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        secante.setText("Método de Secante");
        secante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secanteActionPerformed(evt);
            }
        });
        getContentPane().add(secante, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/metodosnumericos/icono_salir.gif"))); // NOI18N
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 79, 74));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/metodosnumericos/fondo1.jpeg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void biseccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biseccionActionPerformed
        if(evt.getSource() == biseccion){	
            Biseccion abrir=new Biseccion();
            abrir.setVisible(true);
            this.setVisible(false);
	}
    }//GEN-LAST:event_biseccionActionPerformed

    private void secanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secanteActionPerformed
        if(evt.getSource() == secante){	
            Secante abrir=new Secante();
            abrir.setVisible(true);
            this.setVisible(false);
	}
    }//GEN-LAST:event_secanteActionPerformed

    private void newtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newtonActionPerformed
        if(evt.getSource() == newton){	
            NewtonRaphson abrir=new NewtonRaphson();
            abrir.setVisible(true);
            this.setVisible(false);
	}
    }//GEN-LAST:event_newtonActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuMetodos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuMetodos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuMetodos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuMetodos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuMetodos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton biseccion;
    private javax.swing.JButton fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton newton;
    private javax.swing.JButton salir;
    private javax.swing.JButton secante;
    // End of variables declaration//GEN-END:variables
}
